spring:

  jpa:
    properties:
      hibernate:
        format_sql : true
        highlight_sql : true
        use_sql_comments: true
        default_batch_fetch_size: 500

  datasource:
    url: jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:6543/postgres
    username: postgres.ufkrrzcfwlvxdonidpfz
    password: 6QPOudb5YT5lm732

  servlet:
    multipart:
      enabled : true
      max-file-size : 2MB
      max-request-size : 5MB

logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace


      springframework:
        security: debug


auth:
  jwt:
    issuer: team.sparta.com
    secret: b5aM8dP2lR4sV1xQ0eZ6wH3gT9uC7nK5
    accessTokenExpirationHour : 1680

supabase:
  url : "https://ufkrrzcfwlvxdonidpfz.supabase.co"
  key : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVma3JyemNmd2x2eGRvbmlkcGZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDU5MDU1NjUsImV4cCI6MjAyMTQ4MTU2NX0.pLu0EUQtRMBXId1WrX6bXTO8R-XID-T-4eQJP-0t5HA"


