spring:

  jpa:
    properties:
      hibernate:
        format_sql : true
        highlight_sql : true
        use_sql_comments: true
        default_batch_fetch_size: 500

  servlet:
    multipart:
      enabled : true
      max-file-size : 2MB
      max-request-size : 5MB

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 715849965814-g5lltfgihfspouqam9m7qjntmm37e109.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace


      springframework:
        security: debug


auth:
  jwt:
    issuer: team.sparta.com
    secret: b5aM8dP2lR4sV1xQ0eZ6wH3gT9uC7nK5
    accessTokenExpirationHour : 1680

supabase:
  url : "https://ufkrrzcfwlvxdonidpfz.supabase.co"
  key : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVma3JyemNmd2x2eGRvbmlkcGZ6Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcwNTkwNTU2NSwiZXhwIjoyMDIxNDgxNTY1fQ.gbMZkTLOQ5AQGU0YbCekxruTpsliYeAK3qitmFP4gBQ"


