spring:
  jpa:
    properties:
      hibernate:
        format_sql : true
        highlight_sql : true
        use_sql_comments: true
        default_batch_fetch_size: 500
  datasource:
    url: jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:6543/postgres
    username: postgres.ufkrrzcfwlvxdonidpfz
    password: 6QPOudb5YT5lm732

logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace


      springframework:
        security: debug


auth:
  jwt:
    issuer: team.sparta.com
    secret: b5aM8dP2lR4sV1xQ0eZ6wH3gT9uC7nK5
    accessTokenExpirationHour : 1680